package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Reads patient data from text files generated by the simulator's file output strategy.
 * Each file in the directory contains lines in the format:
 * "Patient ID: {id}, Timestamp: {ts}, Label: {label}, Data: {value}"
 */
public class FileDataReader implements DataReader {

    private final String directory;

    /**
     * @param directory path to the directory containing simulator output files
     */
    public FileDataReader(String directory) {
        this.directory = directory;
    }

    /**
     * Reads all .txt files in the configured directory and loads the records
     * into the given DataStorage. Lines that cannot be parsed are skipped.
     *
     * @param dataStorage the storage to populate with the parsed records
     * @throws IOException if the directory does not exist or cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File dir = new File(directory);
        if (!dir.exists() || !dir.isDirectory()) {
            throw new IOException("Output directory not found: " + directory);
        }

        File[] files = dir.listFiles((d, name) -> name.endsWith(".txt"));
        if (files == null) return;

        for (File file : files) {
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    parseLine(line, dataStorage);
                }
            }
        }
    }

    /**
     * Parses a single line from a simulator output file and adds the record to storage.
     * Lines with non-numeric data values (e.g. "triggered", "resolved") are skipped.
     *
     * @param line        a line from the output file
     * @param dataStorage the storage to add the parsed record to
     */
    private void parseLine(String line, DataStorage dataStorage) {
        try {
            // Expected format: Patient ID: 1, Timestamp: 1714376789050, Label: Saturation, Data: 98.0%
            String[] parts = line.split(", ");
            int patientId = Integer.parseInt(parts[0].split(": ")[1].trim());
            long timestamp = Long.parseLong(parts[1].split(": ")[1].trim());
            String label = parts[2].split(": ")[1].trim();
            String dataStr = parts[3].split(": ")[1].trim();

            // Strip any non-numeric suffix (e.g. "%" in saturation readings)
            dataStr = dataStr.replaceAll("[^0-9.\\-]", "");
            if (dataStr.isEmpty()) return; // skip non-numeric data like "triggered"

            double value = Double.parseDouble(dataStr);
            dataStorage.addPatientData(patientId, value, label, timestamp);
        } catch (Exception e) {
            System.err.println("Skipping malformed line: " + line);
        }
    }
}
