package com.alerts;

/**
 * Represents an alert generated by the monitoring system when a patient's
 * health data breaches a predefined threshold or condition.
 *
 * <p>An alert captures who it concerns ({@code patientId}), what triggered it
 * ({@code condition}), and when it occurred ({@code timestamp}).</p>
 */
public class Alert {

    private String patientId;
    private String condition;
    private long timestamp;

    /**
     * Constructs a new Alert.
     *
     * @param patientId the ID of the patient this alert concerns
     * @param condition a short description of the condition that triggered the alert
     * @param timestamp the time the alert was generated, in milliseconds since epoch
     */
    public Alert(String patientId, String condition, long timestamp) {
        this.patientId = patientId;
        this.condition = condition;
        this.timestamp = timestamp;
    }

    /**
     * Returns the ID of the patient this alert concerns.
     *
     * @return the patient ID
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * Returns a short description of the condition that triggered this alert.
     *
     * @return the condition string
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Returns the time this alert was generated.
     *
     * @return timestamp in milliseconds since epoch
     */
    public long getTimestamp() {
        return timestamp;
    }
}
